### ISSUE TITLE
TD: Streamline coverage reports

### ISSUE THREAD

**Issue by zFernand0** [zowe/cics-for-zowe-client#86]
**Is your feature or enhancement request related to a problem or limitation? Please describe**

We used to have coverage reports for the CICS CLI plug-in

**Describe your enhancement idea**

We should split the coverage results, that way the coverage config can be implemented like this:
```yaml
 "zowe/cics-for-zowe-client#main":
    unit:
      junit-artifact: main.yml/cics-cli/unit
      lcov-artifact: main.yml/cics-cli/unit/coverage
    unit-sdk:
      junit-artifact: main.yml/cics-sdk/unit
      lcov-artifact: main.yml/cics-sdk/unit/coverage
    unit-vsce:
      junit-artifact: main.yml/cics-vsce/unit
      lcov-artifact: main.yml/cics-vsce/unit/coverage
```

**Describe alternatives you've considered**

Manually providing coverage information to requesters 

**Provide any additional context**

For more details, see the [coverage-config.yaml in the standalone repository](https://github.com/zowe/zowe-cli-standalone-package/blob/master/coverage-config.yaml#L22).
